# ServiceAccount for Hub cluster to authenticate to Spoke
apiVersion: v1
kind: Namespace
metadata:
  name: hub-consumers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-consumer-sa
  namespace: hub-consumers
