apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hub-consumer-sa.yaml
  - dummy-credentials.yaml
  - maas-model-ref.yaml
  - maas-auth-policy.yaml
  - maas-subscription.yaml
