apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: hub-tinyllama
  namespace: models-as-a-service
spec:
  modelRef:
    kind: ExternalModel
    name: hub-multicluster-model
